name: KBAnalysis
on:
  issues:
    types:
     - opened
     - reopened
     - closed
permissions:
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: step-security/secure-workflows
    
      - name: KBAnalysis
        uses: step-security/secure-workflows/kbanalysis@d666fc708809b1113891ce92b53a8512cf1c4483 # main
        with:
          github-token: ${{secrets.PAT }}
          issue-id: ${{ github.event.issue.number}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          token: ${{secrets.PAT}} #  need to use PAT since GITHUB_TOKEN does not initiate workflows
          body: "Fixes #${{github.event.issue.number}}"
          commit-message: "added KB for issue#${{github.event.issue.number}}"
          title: "Add KB for issue${{github.event.issue.number}}"
          branch: "issue#${{github.event.issue.number}}"
